### ISSUE TITLE
Добавить интеграцию Sentry

### ISSUE THREAD

**Issue by KristobalJunta** [groupbwt/scrapy-boilerplate#25]
https://pypi.org/project/scrapy-sentry-sdk/

**Comment by DmitryKovtun** [comment]
Также потребуется поднять версию скрапи до 2.0+

**Comment by DmitryKovtun** [comment]
Пакет с сентри конфликтует с scrapy_new
sentry_sdk юзает скрапи<2.0
scrapy_new юзает скрапи >=2.0
