### ISSUE TITLE
Ошибка в rmq_errback

### ISSUE THREAD

**Issue by AntonGsv** [groupbwt/scrapy-boilerplate#46]
on_item_scheduled принимает обязательный параметр **response**, в декораторе передается параметр failure=response.
Нужно передавать response=None - т.к. response в данном контексте  Failure класс.

**Comment by AntonGsv** [comment]
**src/rmq/extensions/rpc_task_consumer.py**

метод **on_item_scraped** может принимать не только объект Response но и объект Failure если item был передан из errback функции, текущая реализация выполняется с ошибками для такого сценария.

**Comment by AntonGsv** [comment]
> метод on_item_scraped может принимать не только объект Response но и объект Failure если item был передан из errback функции, текущая реализация выполняется с ошибками для такого сценария.
Возможно на счет этого ошибся, воссоздать не получилось

**Comment by tyorn** [comment]
декораторы в скором времени будут выпелены и заменены мидлварой. по идее с ней даже ситуации такой не должно быть.
