### ISSUE TITLE
Ошибка резолвинга зависимостей с текущей версией pyproject

### ISSUE THREAD

**Issue by KristobalJunta** [groupbwt/scrapy-boilerplate#51]
На данный момент (коммит 195ffc56) poetry не может установить зависимости
Ошибка:
```
[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

На данный момент непонятна причина, но если зафиксировать версию Scarpy (например, `scrapy = "2.2.1"`) - то проблема уходит.

**Comment by tyorn** [comment]
пока зафиксировал версию на "2.2.1"
