### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by KristobalJunta** [groupbwt/scrapy-boilerplate#9]
Улучшения касательно обеспечения качества кода:

- [x] добавить [isort](https://github.com/timothycrosley/isort)
- [x] добавить [dotenv linter](https://github.com/wemake-services/dotenv-linter)
- [x] добавить mypy

**Comment by DmitryKovtun** [comment]
Добавил dotenv-linter в проект. 
У пакета нет pre-commit-hooks.yaml, потому не получится запускать его вместе с остальными в pre-commit.

C mypy такая же проблема, только там есть зеркало от разработчиков pre-commit. 
Варианты решения: 
- самостоятельно создать такое зеркало для dotenv-linter
- сделать pre-commit-hooks.yaml и попробовать pull request в исходный репозиторий

**Comment by KristobalJunta** [comment]
@DmitryKovtun спасибо
Для dotenv-linter держать свое зеркало не вижу смысла. Пока что отправил им issue, а там посмотрим.
https://github.com/wemake-services/dotenv-linter/issues/205
