### ISSUE TITLE
deploy.sh stops all pm2 processes when no $3 is set

### ISSUE THREAD

**Issue by DmitryKovtun** [groupbwt/scrapy-boilerplate#90]
Missed to set PREFIX value in gitlab variables and auto-deploy script deleted all pm2 processes on the server.

There should be some kind of condition to verify whether $3 has value and only then delete processes.
https://github.com/groupbwt/scrapy-boilerplate/blob/082085990455c7102eb822f6240a30d21e8809ea/deploy.sh#L42

**Comment by AntonGsv** [comment]
Добавил проверку в deploy.py.
